docs/source/_templates/custom-class-template.rst, docs/source/api/nn/index.rst, docs/source/conf.py, mlx_graphs/data/data.py, mlx_graphs/nn/conv/gat_conv.py, mlx_graphs/nn/conv/gcn_conv.py, mlx_graphs/nn/graph_network_block.py, mlx_graphs/nn/linear.py, mlx_graphs/nn/message_passing.py, mlx_graphs/nn/pooling/global_pooling.py, mlx_graphs/utils/array_ops.py, mlx_graphs/utils/inits.py, mlx_graphs/utils/scatter.py, mlx_graphs/utils/sorting.py, mlx_graphs/utils/topology.py, mlx_graphs/utils/transformations.py, pyproject.toml
Fixing https://github.com/TristanBilot/mlx-graphs/issues/35 and refactoring docs. 
I added the `sphinx-autodoc-typehints` plugin so that types in docstrings are directly inferred from the function signatures. This is in line with PEP484.
=> Update and refactor docs

docs/source/_templates/data-class-template.rst, docs/source/api/data/batch.rst, docs/source/api/data/data.rst
=> add data template and docs

docs/source/api/utils/validators.rst, mlx_graphs/data/batch.py, mlx_graphs/utils/validators.py, tests/utils/test_validators.py
Fix `validate_list_of_graph_data` to check argument is a `list[GraphData]` + tests + docs
=> Fix and test graphs validator

docs/source/api/utils/transformations.rst, mlx_graphs/utils/transformations.py, tests/utils/test_transformations.py
Functions to add and remove self loops (https://github.com/TristanBilot/mlx-graphs/issues/38)
=> Add and remove self loops

mlx_graphs/data/data.py, tests/data/test_data.py
https://github.com/TristanBilot/mlx-graphs/issues/48
=> GraphData __repr__

.github/workflows/push_update_docs.yml, docs/source/conf.py, pyproject.toml
making mlx install work only on darwin
=> Fix sphinx build

README.md, docs/source/install.rst
Updating installation instructions for pypi.
=> update installation instructions with pypi

mlx_graphs/utils/scatter.py, pyproject.toml, tests/data/test_data.py, tests/nn/conv/test_gat_conv.py, tests/nn/conv/test_gcn_conv.py, tests/nn/conv/test_gin_conv.py, tests/nn/conv/test_sage_conv.py, tests/nn/pooling/test_pooling.py
Upgrading to mlx 0.1 (https://github.com/TristanBilot/mlx-graphs/issues/66).
=> migrate to mlx 0.1

README.md, pyproject.toml
=> upgrade to mlx 0.2

README.md, docs/source/api/data/dataloaders.rst, docs/source/api/data/index.rst, mlx_graphs/data/__init__.py, mlx_graphs/data/dataloaders.py, mlx_graphs/datasets/dataset.py, tests/data/test_batch.py, tests/data/test_data.py, tests/data/test_dataloaders.py, tests/utils/test_validators.py
Implementing a very basic Dataloader working with `Dataset` and `Sequence[GraphData]` with basic shuffling options and batching.
There are probably many ways to improve efficiency that we can implement later.
=> Basic Dataloader

.gitignore, docs/source/api/datasets/index.rst, docs/source/api/utils/array_ops.rst, docs/source/api/utils/transformations.rst, docs/source/index.rst, docs/source/tutorials/quickstart.rst, mlx_graphs/data/collate.py, mlx_graphs/data/data.py, mlx_graphs/data/dataloaders.py, mlx_graphs/datasets/__init__.py, mlx_graphs/datasets/dataset.py, mlx_graphs/datasets/karate_club.py, mlx_graphs/datasets/qm7b.py, mlx_graphs/datasets/tu_dataset.py, mlx_graphs/datasets/utils.py, mlx_graphs/datasets/utils/__init__.py, mlx_graphs/datasets/utils/download.py, mlx_graphs/datasets/utils/io.py, mlx_graphs/utils/__init__.py, mlx_graphs/utils/array_ops.py, mlx_graphs/utils/transformations.py, tests/conftest.py, tests/data/test_data.py, tests/datasets/test_dataset.py, tests/datasets/test_karate_club.py, tests/datasets/test_qm7b.py, tests/datasets/test_tu_dataset.py, tests/utils/test_transformations.py
=> More datasets (QM7b, TU)

pyproject.toml
Upgrade mlx dependency to v0.4
=> upgrade mlx version

mlx_graphs/nn/conv/gcn_conv.py, tests/nn/conv/test_gcn_conv.py
Enable self-loops for the GCNConv layer.
=> GCNConv self loops

docs/source/api/utils/convert.rst, docs/source/api/utils/index.rst, mlx_graphs/utils/convert.py, tests/utils/test_convert.py
Simple utility function to convert an mlx GraphData object to a networkx object to facilitate visualisation of subgraphs of Neighbor Sampler (#94)
=> Convert to nx

mlx_graphs/datasets/tu_dataset.py, mlx_graphs/datasets/utils/io.py
Fixing the `TUDataset` as it wasn't loading node and edge attributes.
=> TUDataset fix

.github/workflows/push_update_docs.yml, docs/source/conf.py, pyproject.toml
=> v0.0.4 release

docs/source/api/datasets/index.rst, mlx_graphs/datasets/__init__.py, mlx_graphs/datasets/ogb_dataset.py
Implementing OGB datasets. Closes #127 
=> ogb dataset

mlx_graphs/datasets/tu_dataset.py
=> fix TUDataset

mlx_graphs/datasets/ogb_dataset.py
Closes #136 avoiding runtime type checks.
=> explicit ALL_DATASETS in OGBDataset

docs/source/_templates/dataset-class-template.rst, docs/source/_templates/datasets-class-template.rst, docs/source/api/datasets/index.rst, mlx_graphs/datasets/__init__.py, mlx_graphs/datasets/dataset.py, mlx_graphs/datasets/ogb_dataset.py, mlx_graphs/datasets/planetoid.py, mlx_graphs/datasets/qm7b.py, mlx_graphs/datasets/superpixel.py, tests/datasets/test_dataset.py, tests/datasets/test_planetoid.py
Implementing `save` and `load` for datasets with `pickle`.
Closes #96.
=> Save processed Dataset

docs/source/api/datasets/index.rst, mlx_graphs/datasets/__init__.py, mlx_graphs/datasets/elliptic.py, pyproject.toml, tests/datasets/test_elliptic.py
Based on pytorch's version for elliptic bitcoin dataset
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/elliptic.html
=> Add Elliptic bitcoin dataset

docs/source/_templates/transform-class-template.rst, docs/source/api/transforms/index.rst, docs/source/index.rst, mlx_graphs/datasets/dataset.py, mlx_graphs/datasets/elliptic.py, mlx_graphs/transforms/__init__.py, mlx_graphs/transforms/base_transform.py, mlx_graphs/transforms/normalize_features.py, tests/transforms/test_normalize_features.py
Body: Added Normalized feature transform and base transforms.
1. Added unit tests for Normalize features
2. Ran pre-commit steps
This can be a potential fix for #149
To have `pre_transform/transform` as a feature step for preprocessing data before loading
Implemented Normalized features which normalizes `node_features` of graph data
=> Add Normalized features and base transforms

mlx_graphs/data/data.py, tests/data/test_data.py
Adding `is_directed` and `is_undirected` methods to `GraphData`. Closes #114.
=> add is_directed and is_undirected to GraphData

docs/source/api/nn/index.rst, mlx_graphs/nn/__init__.py, mlx_graphs/nn/norm/__init__.py, mlx_graphs/nn/norm/batch_norm.py, mlx_graphs/nn/norm/instance_norm.py, mlx_graphs/nn/norm/layer_norm.py, mlx_graphs/utils/transformations.py, pyproject.toml, tests/nn/norm/test_batch_norm.py, tests/nn/norm/test_instance_norm.py, tests/nn/norm/test_layer_norm.py
Added normalizations to improve stability of models during training
- Added batch Normalization to normalize features across batch
- Added layer normalization to normalize features across layers
- Added Instance normalization to normalize individual node features in a graph
Added normalizations to improve stability during training
=> Implement Batch, Layer, Instance normalization

benchmarks/framework_comparison/random_walks/launcher.py, benchmarks/framework_comparison/random_walks/results.md, benchmarks/framework_comparison/random_walks/setup_mlx.py, benchmarks/framework_comparison/random_walks/setup_numpy.py, benchmarks/framework_comparison/random_walks/setup_torch_cluster.py, benchmarks/framework_comparison/random_walks/utils.py, benchmarks/random_walk_benchmark/Random-walk_benchmarks.ipynb, pyproject.toml
Added some benchmarks for random walks which were generated by mlx, torch and numpy
Added some benchmarks to compare torch_cluster, mlx and numpy
=> Rudimentry benchmarks for mlx and torch_cluster
